Add CookieSigner class
yiisoft/cookies pull request #19
Opened 2021-03-04 11:37 UTC by devanych

| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Fixed issues  | #4, https://github.com/yiisoft/user/issues/30

2021-03-04 11:53 UTC, samdark requested changes

2021-03-04 11:53 UTC, samdark commented on src/CookieSigner.php
> +    public function unsign(Cookie $cookie): Cookie
```suggestion
    public function validate(Cookie $cookie): Cookie
```

2021-03-04 11:53 UTC, samdark commented on src/CookieSigner.php
> +     * Returns a new cookie instance with the unsigned cookie value.
```suggestion
     * Returns a new cookie instance with the clean cookie value or throws an exception if signature is not valid.
```

2021-03-04 11:53 UTC, samdark commented on src/CookieSigner.php
> +    public function validate(Cookie $cookie): bool
I don't think it's useful.

2021-03-04 15:28 UTC, samdark approved these changes

2021-03-04 19:59 UTC, roxblnfk approved these changes

2021-03-04 19:59 UTC, roxblnfk commented on src/CookieSigner.php
> +        return $this->signatureLength === strlen($signature) && preg_match('/^[0-9a-f]+$/', $signature);
```suggestion
        return $this->signatureLength === strlen($signature) && preg_match('/^[0-9a-f]+$/', $signature) === 1;
```

2021-03-04 19:59 UTC, roxblnfk commented on src/CookieSigner.php
> +    private const SEPARATOR = '__';
You can use more short separator

2021-03-04 23:16 UTC, samdark requested changes

2021-03-04 23:16 UTC, samdark commented on README.md
> +- signs a cookie to prevent its value from being tampered
```suggestion
- signs a cookie to prevent its value from being tampered with
```

2021-03-04 23:16 UTC, samdark commented on README.md
> +Signing a cookie to prevent its value from being tampered:
```suggestion
Signing a cookie to prevent its value from being tampered with:
```

2021-03-04 23:16 UTC, samdark commented on README.md
> +// Prefixes unique hash based on the value of the cookie.
```suggestion
// Prefixes unique hash based on the value of the cookie and a secret key.
```

2021-03-04 23:16 UTC, samdark commented on src/CookieSigner.php
> + * A CookieSigner signs the cookie value and validates whether the signed cookie value has been tampered.
```suggestion
 * A CookieSigner signs the cookie value and validates whether the signed cookie value has been tampered with.
```

2021-03-04 23:16 UTC, samdark commented on src/CookieSigner.php
> +     * The signature separator and the cookie value.
```suggestion
     * The separator used between a signature and a cookie value.
```

2021-03-04 23:16 UTC, samdark commented on src/CookieSigner.php
> +     * @param Mac|null $mac If the null, the Mac instance with the default hashing algorithm will be created.
```suggestion
     * @param Mac|null $mac If null, the Mac instance with the default hashing algorithm will be created.
```

2021-03-04 23:16 UTC, samdark commented on src/CookieSigner.php
> +     * @param Cookie $cookie The cookie with unsigned value.
```suggestion
     * @param Cookie $cookie The cookie with plain value.
```

2021-03-04 23:16 UTC, samdark commented on src/CookieSigner.php
> +     * @throws RuntimeException If the cookie value is tampered. If you are not sure that
```suggestion
     * @throws RuntimeException If the cookie value is tampered with. If you are not sure that
```

2021-03-05 20:45 UTC, roxblnfk commented on src/CookieSigner.php
> +        return strpos($cookie->getValue(), $this->prefix($cookie)) === 0;
```suggestion
        return strlen($cookie->getValue()) > 32 && strpos($cookie->getValue(), $this->prefix($cookie)) === 0;
```

2021-03-10 21:23 UTC, samdark approved these changes

2021-03-10 21:24 UTC, merged